---
version: "3.4"
services:
  khali:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 15432:5432
    volumes:
      - db:/var/lib/postgresql:data
      - ./db:/db
volumes:
  db:
    driver: local
